// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smdjmmefqherrlxcqfhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtZGptbWVmcWhlcnJseGNxZmhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzE4MTIsImV4cCI6MjA2NTMwNzgxMn0.fz12YjHpA3m2whBtMo7q-mBHv3wL3AjfZ4nZZHKWzVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);